export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const CREATE_COURSE = "CREATE_COURSE";
export const REMOVE_COURSE = "REMOVE_COURSE";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
